import turtle
p=turtle.Turtle()
p.getscreen().bgcolor('red')
p.color('yellow')
p.penup()
p.goto(-100,100)
p.pendown()
p.begin_fill()
for i in range(5):
    p.forward(200)
    p.left(216)
p.end_fill()
p.penup()
p.goto(-200,200)
p.pendown()
p.forward(400)
p.right(90)
p.forward(250)
p.right(90)
p.forward(400)
p.right(90)
p.forward(250)
turtle.done()